--- Running scipy.sparse.linalg.splu#18NN/spluNN, strategy: relancer
[ERR MSG]: OrderedDict([('project', 'scipy.sparse.linalg.splu#18NN'), ('notebook', 'spluNN'), ('text', '  File "spluNN.py", line 4, in <module>\n    lu = splu(A,  \'MMD_AT_PLUS_A\', diag_pivot_thresh=0.1, drop_tol=0.2, relax=1.0)\nTypeError: splu() got an unexpected keyword argument \'drop_tol\'\n')])
  File "spluNN.py", line 4, in <module>
Error inducing API short name: splu, line no: 4
Error inducing API fqn: scipy.sparse.linalg.splu, line no: 4
*** TypeError: PLACEHOLDER
Repair Action: arg_name
Key Params: ['IMPLICIT_0', 'IMPLICIT_1', 'diag_pivot_thresh', 'drop_tol', 'relax']
Prev Params: None
Prev Repair Action: None
Line No: 4
Prev Line No: 0
GitHub Candidates:
[]
KP:['IMPLICIT_0', 'IMPLICIT_1', 'diag_pivot_thresh', 'drop_tol', 'relax']
EXPP: ['IMPLICIT_0', 'IMPLICIT_1', 'diag_pivot_thresh', 'drop_tol', 'relax']
APIDoc Candidates:
[]
All Solution Candidates:
[]
[INFO] This case cannot be fixed!


real	0m0.551s
user	0m1.796s
sys	0m6.655s
