--- Running pandas.DataFrame.resample#103NN/resampleNN, strategy: relancer
[ERR MSG]: OrderedDict([('project', 'pandas.DataFrame.resample#103NN'), ('notebook', 'resampleNN'), ('text', '  File "resampleNN.py", line 4, in <module>\n    DataFrame.resample(\'3T\', axis=0, closed=None, label=None, convention=\'start\', kind=None, loffset=None, base=None, on=None, level=None, origin=\'start_day\', offset=None, group_keys=False).sum()\nTypeError: resample() got an unexpected keyword argument \'loffset\'\n')])
  File "resampleNN.py", line 4, in <module>
Error inducing API short name: resample, line no: 4
Error inducing API fqn: UNKNOWN, line no: 4
*** TypeError: PLACEHOLDER
Repair Action: arg_name
Key Params: []
Prev Params: None
Prev Repair Action: None
Line No: 4
Prev Line No: 0
GitHub Candidates:
[]
KP:[]
EXPP: []
APIDoc Candidates:
[]
All Solution Candidates:
[]
[INFO] This case cannot be fixed!


real	0m0.644s
user	0m1.716s
sys	0m5.456s
