--- Running matplotlib.patheffects.SimplePatchShadow#22NN/SimplePatchShadowNN, strategy: relancer
[ERR MSG]: OrderedDict([('project', 'matplotlib.patheffects.SimplePatchShadow#22NN'), ('notebook', 'SimplePatchShadowNN'), ('text', '  File "SimplePatchShadowNN.py", line 5, in <module>\n    pe_shadow = pe.SimplePatchShadow((3, -3),  \'gray\',  None,  0.2,  0.5,  None)\nTypeError: __init__() takes from 1 to 5 positional arguments but 7 were given\n')])
  File "SimplePatchShadowNN.py", line 5, in <module>
Error inducing API short name: SimplePatchShadow, line no: 5
Error inducing API fqn: matplotlib.patheffects.SimplePatchShadow, line no: 5
*** TypeError: PLACEHOLDER
Repair Action: arg_name
Key Params: ['IMPLICIT_0', 'IMPLICIT_1', 'IMPLICIT_2', 'IMPLICIT_3', 'IMPLICIT_4', 'IMPLICIT_5']
Prev Params: None
Prev Repair Action: None
Line No: 5
Prev Line No: 0
GitHub Candidates:
[]
KP:['IMPLICIT_0', 'IMPLICIT_1', 'IMPLICIT_2', 'IMPLICIT_3', 'IMPLICIT_4', 'IMPLICIT_5']
EXPP: ['IMPLICIT_0', 'IMPLICIT_1', 'IMPLICIT_2', 'IMPLICIT_3', 'IMPLICIT_4', 'IMPLICIT_5']
APIDoc Candidates:
[]
All Solution Candidates:
[]
[INFO] This case cannot be fixed!


real	0m0.705s
user	0m1.812s
sys	0m5.794s
