--- Running scipy.integrate.solve_ivp#35YY/solve_ivpYY, strategy: relancer
[ERR MSG]: OrderedDict([('project', 'scipy.integrate.solve_ivp#35YY'), ('notebook', 'solve_ivpYY'), ('text', '')])
[INFO] This case is fully fixed!


real	0m0.582s
user	0m3.262s
sys	0m11.604s
