--- Running Response#31NN/ResponseNN, strategy: relancer
[ERR MSG]: OrderedDict([('project', 'Response#31NN'), ('notebook', 'ResponseNN'), ('text', '  File "ResponseNN.py", line 2, in <module>\n    Response(on_close=None, status_code=1)\nTypeError: __init__() got an unexpected keyword argument \'on_close\'\n')])
  File "ResponseNN.py", line 2, in <module>
Error inducing API short name: Response, line no: 2
Error inducing API fqn: httpx.Response, line no: 2
*** TypeError: PLACEHOLDER
Repair Action: arg_name
Key Params: ['on_close', 'status_code']
Prev Params: None
Prev Repair Action: None
Line No: 2
Prev Line No: 0
GitHub Candidates:
[]
KP:['on_close', 'status_code']
EXPP: ['on_close', 'status_code']
APIDoc Candidates:
[]
All Solution Candidates:
[]
[INFO] This case cannot be fixed!


real	0m0.401s
user	0m0.379s
sys	0m0.023s
